name: portfolio_web
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.3
  material_shapes: ^0.0.2
  motor: ^1.1.0
  responsive_framework: ^1.5.1
  responsive_scaler: ^0.1.0
  supabase_flutter: ^2.12.0
  flutter_m3shapes_extended: ^1.0.0
  avatar_glow: ^3.0.1
  m3e_collection: ^0.3.7
  flutter_custom_caraousel_v2: ^0.2.0
  url_launcher: ^6.3.2
  flutter_animate: ^4.5.2
  visibility_detector: ^0.4.0+2
  http: ^1.6.0
  dio: ^5.9.1
  pdfx: ^2.9.2
  open_file: ^3.5.11
  path_provider: ^2.1.5
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/logo/
    - .env

  fonts:
    - family: GoogleSansFlex
      fonts:
        - asset: assets/fonts/GoogleSansFlex-VariableFont_GRAD,ROND,opsz,slnt,wdth,wght.ttf